[versions]

kotlin = "2.0.21"
koin = "3.2.1"
compose-bom = "2024.09.00"
compose-viewmodel = "2.4.1"
compose-lifecycle-runtime = "2.6.0"
compose-material3 = "1.1.1"
nav-animation = "0.28.0"
compose-coil = "2.0.0"
compose-paging = "1.0.0-alpha20"
compose-paging-runtime = "3.2.0-alpha06"
compose-room = "2.5.1"
constraintlayout-compose = "1.0.1"
coroutines = "1.2.1"
androidx-navigation = "2.7.7"
reorderable = "0.9.6"
retrofit = "2.9.0"
converter-gson = "2.9.0"
okhttp = "3.11.0"
timber-version = "4.7.1"
espresso-core = "3.4.0"
accompanist-systemuicontroller = "0.27.0"
junit = "4.13.2"
junit-version = "1.2.1"
appcompat = "1.7.0"

#plugin
agp = "8.9.0"


[libraries]
androidx-core-ktx = {group = "androidx.core", name = "core-ktx", version = "1.13.1" }
koin-core = {group = "io.insert-koin", name = "koin-core", version.ref = "koin"}
koin-android = {group = "io.insert-koin", name = "koin-android", version.ref = "koin"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

compose-bom = {group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom"}
compose-material = {group = "androidx.compose.material", name = "material"}
compose-material3 = {group = "androidx.compose.material3", name = "material3"}
compose-ui-tooling = {group = "androidx.compose.ui", name = "ui-tooling"}
compose-ui-preview = {group = "androidx.compose.ui", name = "ui-tooling-preview"}
compose-lifecycle-runtime = {group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-lifecycle-runtime"}
compose-nav-animation = {group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "nav-animation"}
compose-viewmodel = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-viewmodel"}
compose-koin = {group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin"}
android-navigation-ui = {group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
android-navigation-compose = {group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
compose-page = {group = "com.google.accompanist", name = "accompanist-pager", version = "0.18.0" }


# paging
compose-paging = {group = "androidx.paging", name = "paging-compose", version.ref = "compose-paging"}
compose-paging-runtime = {group = "androidx.paging", name = "paging-runtime", version.ref = "compose-paging-runtime"}

# room
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "compose-room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "compose-room"}
room-paging = {group = "androidx.room", name = "room-paging", version.ref = "compose-room"}

androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }

# coroutines
coroutines-core = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines-android = {group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines"}

# coil
coil-compose = {group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil"}
coil-gif = {group = "io.coil-kt", name = "coil-gif", version.ref = "compose-coil" }
coil-main = {group = "io.coil-kt", name = "coil", version.ref = "compose-coil" }
coil-svg = {group = "io.coil-kt", name = "coil-svg", version.ref = "compose-coil" }

# Network
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# Test
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }

# third party library
sdp-android = {group = "com.intuit.sdp", name = "sdp-android", version = "1.1.0" }
ssp-android = {group = "com.intuit.ssp", name = "ssp-android", version = "1.1.0" }
timber = {group = "com.jakewharton.timber", name = "timber", version.ref = "timber-version"}
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
compose-pullrefresh = {group = "com.github.fengdai.compose", name = "pulltorefresh", version = "0.2.0" }

[plugins]
android-application = {id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = {id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = {id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
