plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.kaiku.composecomponent'
    compileSdk 33

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui.tooling)
    implementation(libs.compose.ui.preview)
    implementation(libs.compose.lifecycle.runtime)
    implementation(libs.compose.material)
    implementation(libs.compose.material3)
    implementation(libs.compose.viewmodel)
    implementation(libs.compose.koin)
    implementation(libs.compose.nav.animation)

    // Paging
    implementation libs.compose.paging
    implementation libs.compose.paging.runtime

    // Koin
    implementation libs.koin.core
    implementation libs.koin.android

    // Room
    implementation libs.room.ktx
    annotationProcessor libs.room.compiler
    implementation libs.room.paging

    // Test
    androidTestImplementation platform(libs.compose.bom)
    debugImplementation libs.compose.ui.tooling
    debugImplementation libs.compose.ui.preview
    testImplementation libs.junit
    androidTestImplementation libs.androidx.ui.test.junit4
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core

    implementation libs.accompanist.systemuicontroller

    //ConstraintLayout
    implementation libs.androidx.constraintlayout.compose

    //network
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.okhttp

    //navigation-compose
    implementation libs.androidx.navigation.compose

    //Coroutines
    implementation libs.coroutines.core
    implementation libs.coroutines.android

    // coil
    implementation(libs.coil.compose)
    implementation(libs.coil.gif)
    implementation(libs.coil.main)
    implementation(libs.coil.svg)

    // Third party
    implementation libs.timber
    implementation libs.reorderable
}